//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios_Palomino.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recarga
    {
        public string Documento { get; set; }
        public string NombreCompleto { get; set; }
        public int ValorRecarga { get; set; }
        public int ValorIncremento { get; set; }
        public int TotalRecarga { get; set; }
    }
}
