//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servicios_Palomino.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Traslado
    {
        public int Codigo { get; set; }
        public Nullable<int> CodigoEmpleado { get; set; }
        public Nullable<int> CodigoProducto { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<System.DateTime> FechaTraslado { get; set; }
        public bool Activo { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
